// suppress inspection "Annotator" for whole file
= Changelog

== Major changes in 3.0
Roboquant version 3.0 has many changes, several of them are breaking changes. The key reason was to clean-up and simplify areas that were a hard to maintain and/or extend. This makes it easier for people to contiue to try new trading ideas and hack their way _roboquant_ if required.

A non-extensive list of the major changes:

- `Policy` is removed. For similar functionality, look at a `SignalStrategy` and `SignalConverter`.

- Signals themselves are also simplified and now use a double value for the rating rather than an enum. This is better suited for more advanced ML type of algos.

- Removed the `Lifecycle` interface including `reset` for all components (Stratyegy, Policy, Broker).

- Order handling is simplified. For example, order-ids are handout by the broker (during the place order method). So they are no longer assigned when creating the order. This is more inline how most brokers work.

- Removed `Roboquant` class. You can now use directly the standalone functions `run` and `runAsync`.

- SimBroker order execution is simplified. Every order type has its own executor that is responsible for every aspect of the execution. A bit less configurable, but much easier to roll your own implementation.

- Improved the `Broker` interface. Only the `broker.sync()` call now provides access to the `account` object.

- `MetricsLogger` is replaced by `Journal` and `MetricsJournal`. Journal has access to more data (also new orders).
+
[source,kotlin]
----
fun track(event: Event, account: Account, orders: List<Order>) {
    TODO()
}
----
+
Also more clear separation of concerns since multi-run logging logic is now handled by a seperate class.

- Hearth-beat generation for live feeds now done at consumer level via a time-out. This avoids a lot of possible errors and complications when nesting live feeds.

- Better naming convention for many classes/attributes. Two main ones are:
    * Event `actions` are now called `items`.
    * `Instruction` is now the interface for `Order`, `Cancellation` and `Modification`

- For the time being removed the machine learning module. Rethinking what frameworks to use for future ML algo trading.

- Removed the `roboquant-binance` module. It was using an old unsupported Binance API. And since Binance no longer operate in my country, it is difficult to moving to the newer API without be able to test it.

+
[source,kotlin]
----
val strategy = EMAStrategy()
val feed = CSVFeed("data/US")

// old approach
val roboquant = Roboquant(strategy)
roboquant.run(feed)

// new approach
val account = run(feed, strategy)
----

- Use the new Alpaca library that is based on published OpenAPI specification.

- Simplified AvroFeed (have to see if this is not too simple). We had to drop the `feed.assets` method to make this possible.

- Updated most of the dependencies. We only not yet moved to Kotlin 2.0 since Jupyter Notebooks are not yet supported.

- Removed the `Summary` functionality. This required relative a lot of code and maintenance and now replaced by a simpler toString() implementation.
