= Changelog

== Major changes in 3.0
Roboquant version 3.0 has several changes, several of them are breaking changes (but similar or better functionality).

- Signals are simplified and now use a double value for the rating rather than an enum. This is better suited for more advanced ML type of algos.

- Removed the `Lifecycle` interface for all components (Stratyegy, Policy, Broker).

- Order ids are handout by the broker (during the place order method), so not assigned when creating the order. This is more inline how
most brokers work.

- Improved the broker interface. Only the `broker.sync()` call now provides access to the `account` object.

- `MetricsLogger` is replaced by `Journal` and `MetricsJournal`. Journal has access to more data (also signals and new orders).
+
[source,kotlin]
----
fun track(event: Event, account: Account, signals: List<Signal>, orders: List<Order>) {
    TODO()
}
----
+
Also more clear separation of concerns since multi-run logging logic is now handled by a seperate class.

- Simplified hearth-beat generation on an event channel (now done at consumer level via a time-out). This avoids a lot of possible errors and complications when nesting feeds.

- Better naming convention for many classes/attributes. Main one is event `actions` are now called `items`.

- For the time being removed the machine leanring module. Rethinking what frameworks to use for future ML algo trading.

- You can now start a run using the `org.roboquant.run` function. So no need to instantiate a Roboquant class anymore. The `run` also returns the latest `account` object. The run method also displays a progress bar if desired.
+
[source,kotlin]
----
val strategy = EMAStrategy()
val feed = CSVFeed("data/US")

// old approach
val roboquant = Roboquant(strategy)
roboquant.run(feed)

// new approach
val account = run(feed, strategy)
----

- Use the new Alpaca API based on published OpenAPI specification.

- Simplified AvroFeed (have to see if thsi is not too simple)

- Updated almost all dependencies. Only not yet moved to Kotlin 2.0 since Jupyter Notebooks are not yet supported.

- Removed most of `Summary` funcitonality. This was reletive a lot of maintenance and now replaced with a simpler toString() implementation.
