= Installation
:icons: font

There are two ways to use roboquant:

. Interactively in a Jupyter notebook. If you want to get up and running quickly, and want to experiment with many strategies, this is the best approach. Additionally, you get many charts out-of-the-box.

. As a library in your own Kotlin or Java application. If you plan to develop large and complex trading strategies, this is the good approach since you have the full power of an IDE like IntelliJ IDEA at your disposal.

== Jupyter Notebook
If you have already Docker installed, it only takes a single command to have a fully functional Jupyter Lab environment available:

[source,shell]
----
docker run --rm -p 8888:8888 roboquant/jupyter
----

This will pull the image from DockerHub and run it on your local machine. The image comes with several notebooks that demonstrate how to develop and run your own strategies.

If you don't have Docker yet installed on your computer, check out https://www.docker.com/get-started[Docker get started] and download Docker for Desktop from there. If you are running Linux, then your distribution likely already has Docker included.

If you don't want to install anything locally, you can:

. Try some same notebooks right now in your browser by clicking: image:https://mybinder.org/badge_logo.svg[Binder,link=https://mybinder.org/v2/gh/neurallayer/roboquant-notebook/main?urlpath=lab/tree/tutorials]

. Go to https://datalore.jetbrains.com/[JetBrains Datalore] and create an account there. It supports Kotlin Notebooks and has a free tier available if you just want to try it out.


== Standalone Application
Just add `roboquant` as a dependency to your build tool, like Maven or Gradle.

*Maven*

[source,xml]
----
<dependency>
    <groupId>org.roboquant</groupId>
    <artifactId>roboquant</artifactId>
    <version>VERSION</version>
</dependency>
----

*Gradle*
// file:noinspection GrUnresolvedAccess
[source, groovy]
----
implementation group: 'org.roboquant', name: 'roboquant', version: 'VERSION'
----

Next to `roboquant`, the following additional artefacts are available for inclusion in your application:

* *roboquant-crypto* Adds support for many of today's most popular crypto exchanges
* *roboquant-extra* Adds out-of-the-box integrations with 3rd party brokers and market data providers.
* *roboquant-ta* Adds support for technical analysis indicators and strategies
* *roboquant-jupyter* Adds support for running roboquant inside Jupyter Notebooks
* *roboquant-ibkr* Adds support for Interactive Brokers

== Building from source
First start with cloning the roboquant GitHub repository to your local disk. The quickest way to be up and running is then to install IntelliJ IDEA (either the free community edition or the paid Ultimate version) and open the directory you just cloned. IntelliJ IDEA will recognize it as Kotlin/Maven project, and you can build it and run test directly from the IDE.

_Roboquant_ uses a directory setup that is similar to most other Kotlin projects:

[]
----
root
    submodule1
        src/main/kotlin
        src/test/kotlin
    submodule2
        src/main/kotlin
        src/test/kotlin
----

All source code is written in Kotlin, so there are no Java or other language source files.

Roboquant uses Maven for the build process and assuming you already have this installed, building and installing the libraries locally, is as easy as:

[source,shell]
----
mvn clean install
----

The build and install is tested using JDK 17 runtime, however the generated libraries are targeted against JDK 11 in order to provide better compatibility for projects that still use older versions of the JDK.

TIP: If you plan to make many changes and updates to the source code, checkout the https://github.com/apache/maven-mvnd[Maven Daemon] project that provides much faster builds. It is an almost 100% drop-in replacement of the regular maven and is much faster.

If you want to deploy a release (and not just a SNAPSHOT) to Maven Central, use the `-P release` option. This will then also generate source- and documentation-jar files which are mandatory when deploying a release to Maven Central. It will also always build and deploy the `roboquant-ibkr` module, so you'll need the locally install IBKR Java client library.

[source,shell]
----
mvn clean deploy -P release
----

Of course this requires the having the right credentials for deploying to the Maven Central repo. Also note that `autoReleaseAfterClose` of the `nexus-staging-maven-plugin` is set to false, meaning that if the deployment was sucessfull, you still need to (manually) release the software from staging to production.

== Interactive Brokers
If you don't require integration with Interactive Brokers for your trading, you can skip this step.

Unfortunately it is not allowed to redistribute the Interactive Brokers Java client, so you'll have to download the TwsApi.jar file yourself. You can download the stable version `10.19` from here: https://interactivebrokers.github.io/# and within the downloaded archive file you'll find the required `TwsApi.jar`.


Then install the jar file in the local Maven repository on your machine using the following command:

[source, shell]
----
mvn install:install-file -Dfile=TwsApi.jar -DgroupId=com.interactivebrokers -DartifactId=tws-api -Dversion=10.19 -Dpackaging=jar
----

After this step, you can compile and install the modules including the `roboquant-ibkr` module

[source, shell]
----
mvn install -P ibkr
----

WARNING: If the artefact cannot be found in your local Maven repository during a build, the ibkr profile with the module `roboquant-ibkr` will be skipped.


== Documentation
There is a special `doc` profile to generate documentation and see if there is something missing. You can run the following command to find missing documentation:

[source, shell]
----
mvn dokka:dokka -P doc | grep WARNING
----

Please note the `release` profile has its own dokka task to generate a javadoc jar file.

== Performance Test
To run the built-in performance tests, you can use the following maven command:

[source, shell]
----
./mvnw test -P performance -Dparallel=8
----
The optional `-Dparallel=8` flag determines how many parallel runs to use in the performance test. The default is equal to amount of cores if you don't include this flag. Because the focus is on performance, this test uses a lot more memory than regular back tests.

The output will look something like this:
----
             _______
            | $   $ |             roboquant
            |   o   |             version: 1.2.0-SNAPSHOT
            |_[___]_|             build: 2023-03-01T12:43:08Z
        ___ ___|_|___ ___         os: Mac OS X 13.2.1
       ()___)       ()___)        home: /Users/peter/.roboquant
      // / |         | \ \\       jvm: OpenJDK 64-Bit Server VM 19.0.2
     (___) |_________| (___)      memory: 4096MB
      | |   __/___\__   | |       cpu cores: 8
      /_\  |_________|  /_\
     // \\  |||   |||  // \\
     \\ //  |||   |||  \\ //
           ()__) ()__)
           ///     \\\
        __///_     _\\\__
       |______|   |______|
INFO PerformanceTest - *****    500.000 candlesticks *****
INFO PerformanceTest -     feed filter               10 ms
INFO PerformanceTest -     base run                  87 ms
INFO PerformanceTest -     parallel runs (x8)       184 ms
INFO PerformanceTest -     extended run             571 ms
INFO PerformanceTest -     throughput 21 million candles/s
INFO PerformanceTest - *****  1.000.000 candlesticks *****
INFO PerformanceTest -     feed filter               27 ms
INFO PerformanceTest -     base run                 181 ms
INFO PerformanceTest -     parallel runs (x8)       442 ms
INFO PerformanceTest -     extended run            1598 ms
INFO PerformanceTest -     throughput 18 million candles/s
INFO PerformanceTest - *****  5.000.000 candlesticks *****
INFO PerformanceTest -     feed filter              103 ms
INFO PerformanceTest -     base run                 513 ms
INFO PerformanceTest -     parallel runs (x8)       774 ms
INFO PerformanceTest -     extended run           14420 ms
INFO PerformanceTest -     throughput 51 million candles/s
INFO PerformanceTest - ***** 10.000.000 candlesticks *****
INFO PerformanceTest -     feed filter               92 ms
INFO PerformanceTest -     base run                 709 ms
INFO PerformanceTest -     parallel runs (x8)      1198 ms
INFO PerformanceTest -     extended run           14309 ms
INFO PerformanceTest -     throughput 66 million candles/s
----

The main purpose is to test the performance and stability of the back-test engine itself, not any specific feed, strategy or metric. So the overhead of those type of components is kept to a minimum, while still running full back tests.

== Mutation Testing
Although not enabled by default, roboquant also includes the PIT (see also https://PiTest.org) mutation testing plugin. You can use the following command to invoke it:

[source, shell]
----
mvn test-compile org.pitest:pitest-maven:mutationCoverage
----

PIT runs the unit tests against automatically modified versions of the roboquant code. When the code changes, it should produce different results and cause one or more unit tests to fail. If no unit tests fail at all, it may indicate that the test suite doesn't validate the expected behavior.

In future releases of _roboquant_ it is planned to use mutation testing more in order to improve the overall *real* test coverage.

