= Release planning

== Introduction

There are still many features planned for _roboquant_. For sure the lists on this page are also not complete and new features will pop up over time. Prioritization might shift based also based on community input and contribution.

But at least it gives insight into the current planning when to add certain features. And of course PRs are very welcome and might very well expedite certain features. 

See also the link:CONTRIBUTING.adoc[contributing] page on how to submit a PR.

== Version 0.8.x (end of 2021)

Version 0.8 is all about making sure that (back-)testing works, and the most common use-cases are covered. Much of the foundation for algo trading is in place with this release:

* [x] Improve the documentation in source code
* [x] Improve unit test coverage
* [x] Add visualizations for the Jupyter notebooks
* [x] Improve CSV parsing with extra configurable options
* [x] Improve error messages and warnings to be more helpful
* [x] Add documentation on how to install and get started
* [x] Support for advanced order types
* [x] Add info on key design concepts behind the software, so it becomes easier to contribute
* [x] Bring back Interactive Brokers integration. The code was already developed but due to license restrictions the TwsApi.jar file could not be included with roboquant.
* [x] See how to best fit crypto trading with current account structure

== Version 0.9.x (2022)

Ensure the API is stable and start including AI and Machine Learning support

* [X] Improve documentation, notebooks and examples
* [X] Include demo feeds for quick experimentation
* [X] Use better approach for generating charts

== Version 1.0 (end of 2022)

This version is all about adding stabilizing conecpts and APIs. Although there is already integration available in earlier versions, that is just to validate the architectural concepts and design choices:

* [X] Improve the test coverage
* [X] Stabilize the exposed APIs
* [X] Optimize performance and avoid regressions
* [X] Refactor the order execution simulation
* [X] Improve the running of roboquant notebooks on public infra


== Version 2 and later (2023 and beyond)

The topics mentioned here are some of the ideas for the future releases:

* [ ] Add support for reading different types of data feeds besides price actions
* [ ] Better and more complete integrations with brokers and crypto-exchanges
* [ ] Advanced policies, like auto re-balancing portfolios
* [ ] More ready-to-use strategies out of the box
* [ ] Add more advanced slippage- and fee-models
* [ ] More complex deep learning strategies
* [ ] Right now messages and formats support English format only, add L10N/I18N support
* [ ] Make video(s) that show the steps to develop and test your own strategies
* [ ] Come up with a way users can easily share strategies, code snippets and other best practices