= Release planning

== Introduction

There are still many features planned for _roboquant_. For sure the lists on this page are also not complete and new features will pop up over time. Prioritization might shift based also based on community input and contribution.

But at least it gives insight into the current planning when to add certain features. And of course PRs are very welcome and might very well expedite certain features. 

See also the link:CONTRIBUTING.adoc[contributing] page on how to submit a PR.

== Version 0.8 (end of 2021)

Version 0.8 is all about making sure that (back-)testing works great, and the most common use-cases are covered. Much of the foundation is already in place with this release:

* [x] Improve the documentation in source code
* [x] Improve unit test coverage
* [x] Add visualizations for the Jupyter notebooks
* [x] Improve CSV parsing with extra configurable options
* [x] Improve error messages and warnings to be more helpful
* [x] Add documentation on how to install and get started
* [x] Add info on key design concepts behind the software, so it becomes easier to contribute
* [x] Bring back Interactive Brokers integration. The code is already developed but due to license restrictions the TwsApi.jar file cannot be included with roboquant. So have to come up with alternative solution.

== Version 0.9 (summer 2022)

Ensure the API is stable and start on including AI/ Machine Learning based strategies

* [ ] Stabalize the exposed API
* [ ] Improve documentation based on the stable API
* [ ] Create specific Machine Learning module
* [ ] Add support for distributed learning

== Version 1.0 (end of 2022)

This version is all about adding better live trading capabilities. Although there is already integration available in earlier versions, that is just to validate the architectural concepts supports live trading. These broker integrations are neither reliable nor complete. So what still needs to be done:

* [ ] More complete integrations with brokers and crypto-exchanges
* [ ] Advanced policies, like auto re-balancing portfolios
* [ ] Better margin account simulation support
* [ ] More metrics, especially around alpha and beta calculations
* [ ] See how to best fit crypto trading with current account structure
* [ ] Support additional advanced order types
* [ ] Add more advanced slippage-, fee- and fill-models

== Version 2 and later (2023 and beyond)

The topics mentioned here are just some ideas for the future releases:

* [ ] Add support for reading different types of data feeds besides price info
* [ ] More ready-to-use strategies out of the box
* [ ] More complex deep learning strategies, like LSTM neural networks
* [ ] Right now messages and formats support English format only, add L10N/I18N support
* [ ] Make video(s) that show the steps to develop and test your own strategies
* [ ] Come up with a way users can easily share strategies, code snippets and other best practices